//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.17 at 04:32:59 odp. CEST 
//


package org.dirigent.pattern.builder.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatternStepType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PatternStepType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="File"/>
 *     &lt;enumeration value="JDBCStatement"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PatternStepType")
@XmlEnum
public enum PatternStepType {

    @XmlEnumValue("File")
    FILE("File"),
    @XmlEnumValue("JDBCStatement")
    JDBC_STATEMENT("JDBCStatement");
    private final String value;

    PatternStepType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PatternStepType fromValue(String v) {
        for (PatternStepType c: PatternStepType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
