    
    	/*Create script for dimension D_CUSTOMER*/  
    	CREATE TABLE D_CUSTOMER (
    		CUST_KEY NUMBER(38) PRIMARY KEY,
    		CUST_ID VARCHAR(50),
    		CUST_NAME VARCHAR(100),
    		CUST_ADDRESS_STREET VARCHAR(100),
    		CUST_ADDRESS_CITY VARCHAR(100),
    		CUST_ADDRESS_ZIP VARCHAR(50),
    					
			CUST_VALID_FROM_DATETIME DATE,
			CUST_VALID_TO_DATETIME DATE,
			CUST_CURRENT_FLAG CHAR(1),
			CUST_UPDATED_DATETIME DATE
    	);

		/*Create sequence for generation of surrogate key values.*/   
    	CREATE SEQUENCE CUST_SEQ;
    
    
