--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.855
--   Created On : pátek, 08 říjen, 2010 
--   DBMS       : Oracle 
--   -------------------------------------------------- 



--  Drop Tables, Stored Procedures and Views 

DROP TABLE L0_CUSTOMER CASCADE CONSTRAINTS
;
DROP TABLE L0_CUSTOMER_ADDRESS CASCADE CONSTRAINTS
;
DROP TABLE L0_INVOICE CASCADE CONSTRAINTS
;
DROP TABLE L0_INVOICE_ITEM CASCADE CONSTRAINTS
;
DROP TABLE L0_PRODUCT CASCADE CONSTRAINTS
;
DROP TABLE L0_PRODUCT_GROUP CASCADE CONSTRAINTS
;