//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.26 at 04:47:00 odp. CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/dirigent-pattern/")
package org.dirigent.pattern.builder.jaxb;
